### ISSUE TITLE
Can only filter one smallRNA track at once

### ISSUE THREAD

**Issue by colindaven** [bhofmei/jbplugin-smallrna#1] opened 2016-09-19 12:59 UTC
Hi,

maybe this is by design, but it appears I can only filter one sRNA track using "Filter by size" at once.

Console JS error after selecting second BAM track to filter by size:

dojo.js:837 failed to render menu item: Error: Tried to register widget with id==smrna-select-blue but that id is already registered

If this is a lot of work then I don't know if it is worth fixing, or just educating users (did I miss it in the docs?).

Best wishes,
Colin

**Comment by bhofmei** [comment] 2016-09-19 13:04
Thanks for letting me know. I should have noticed that earlier. Sorry!
It’s not by design. I ran into the same problem with my methylation track plugin and fixed it there. It’s not hard to fix, thankfully. To my knowledge, no one had been using the small RNA plugin so there wasn’t much motivation to check for/fix those things.
Major updating this plugin is the next thing on the list (it’s not behaving properly with the screenshot plugin for some reason and I need to figure that out as well).
I’ll be sure to fix the check boxes later today.

Thanks for using my plugins!
Brigitte

**Comment by bhofmei** [comment] 2016-09-19 14:15
Should be fixed now. Thanks again for pointing that out!

**Closed as completed** 2016-09-19 14:16 UTC

**Comment by colindaven** [comment] 2016-09-19 14:48
Thanks, works great now.
